//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.Unit
{
    using System;
    using System.Collections.Generic;
    
    public partial class UN_CPAT_TRANS_RECORD
    {
        public int TRANS_REC_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string PATIENT_ID { get; set; }
        public string OUT_DEPT_CODE { get; set; }
        public string OUT_DEPT_NAME { get; set; }
        public string IN_DEPT_CODE { get; set; }
        public string IN_DEPT_NAME { get; set; }
        public Nullable<System.DateTime> TRANS_IN_DATE { get; set; }
        public Nullable<System.DateTime> TRANS_OUT_DATE { get; set; }
        public string REASON { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
