//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.Unit
{
    using System;
    using System.Collections.Generic;
    
    public partial class UN_CPAT_NURSE_RECORD
    {
        public int NUR_REC_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string PATIENT_ID { get; set; }
        public Nullable<int> NURSE_TYPE_CODE { get; set; }
        public string NURSE_ITEM_CODE { get; set; }
        public string ITEM_VALUES { get; set; }
        public Nullable<System.DateTime> REC_DATE { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
