//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.Unit
{
    using System;
    using System.Collections.Generic;
    
    public partial class UN_CPAT_DICT_EMPLOYEE
    {
        public string EMP_CODE { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_UID { get; set; }
        public string EMP_PWD { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string PHONE { get; set; }
        public string TITLE { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
