//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.Unit
{
    using System;
    using System.Collections.Generic;
    
    public partial class UN_CPAT_ASSESSMENT_RECORD
    {
        public int ASS_REC_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string PATIENT_ID { get; set; }
        public string AREA_CODE { get; set; }
        public string AREA_NAME { get; set; }
        public string DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string SYMPTOM { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string SCORE { get; set; }
        public string RESULT { get; set; }
        public string VALUE_TYPE { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
