//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.Unit
{
    using System;
    using System.Collections.Generic;
    
    public partial class UN_SD_EPKI_VALUE
    {
        public int SD_EKPI_ID { get; set; }
        public int SD_ID { get; set; }
        public string SD_CODE { get; set; }
        public string SD_CPAT_NO { get; set; }
        public int INDEX_VALUE { get; set; }
        public Nullable<int> RSN_FLAG { get; set; }
        public string UPD_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
