//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.Unit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UTEntities : DbContext
    {
        public UTEntities()
            : base("name=UTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SD_CPAT_DETAIL> SD_CPAT_DETAIL { get; set; }
        public virtual DbSet<SD_CPATS> SD_CPATS { get; set; }
        public virtual DbSet<SD_ITEM_VALUE> SD_ITEM_VALUE { get; set; }
        public virtual DbSet<SD_EPKI_VALUE> SD_EPKI_VALUE { get; set; }
    }
}
