//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.CDR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.EntityClient;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDREntities : DbContext
    {
        public CDREntities(EntityConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection,contextOwnsConnection)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DP_ANESTHESIA_RECORD> DP_ANESTHESIA_RECORD { get; set; }
        public virtual DbSet<DP_ASSESSMENT_RECORD> DP_ASSESSMENT_RECORD { get; set; }
        public virtual DbSet<DP_CHECK_RECORD> DP_CHECK_RECORD { get; set; }
        public virtual DbSet<DP_CONSULT_RECORD> DP_CONSULT_RECORD { get; set; }
        public virtual DbSet<DP_DIAGNOSIS> DP_DIAGNOSIS { get; set; }
        public virtual DbSet<DP_DICT_CHECKTEST> DP_DICT_CHECKTEST { get; set; }
        public virtual DbSet<DP_DICT_DEPT> DP_DICT_DEPT { get; set; }
        public virtual DbSet<DP_DICT_DETAIL> DP_DICT_DETAIL { get; set; }
        public virtual DbSet<DP_DICT_DIAG> DP_DICT_DIAG { get; set; }
        public virtual DbSet<DP_DICT_DRUG> DP_DICT_DRUG { get; set; }
        public virtual DbSet<DP_DICT_EMPLOYEE> DP_DICT_EMPLOYEE { get; set; }
        public virtual DbSet<DP_DICT_MASTER> DP_DICT_MASTER { get; set; }
        public virtual DbSet<DP_EMR_RECORD> DP_EMR_RECORD { get; set; }
        public virtual DbSet<DP_IN_ORDERS> DP_IN_ORDERS { get; set; }
        public virtual DbSet<DP_IN_PATIENT> DP_IN_PATIENT { get; set; }
        public virtual DbSet<DP_INFECTION_RECORD> DP_INFECTION_RECORD { get; set; }
        public virtual DbSet<DP_MEDICAL_RECORD> DP_MEDICAL_RECORD { get; set; }
        public virtual DbSet<DP_NURSE_RECORD> DP_NURSE_RECORD { get; set; }
        public virtual DbSet<DP_OPERATION_RECORD> DP_OPERATION_RECORD { get; set; }
        public virtual DbSet<DP_OUT_EMR> DP_OUT_EMR { get; set; }
        public virtual DbSet<DP_OUT_PATIENT> DP_OUT_PATIENT { get; set; }
        public virtual DbSet<DP_OUT_RECIPE> DP_OUT_RECIPE { get; set; }
        public virtual DbSet<DP_PATHOLOGY_RECORD> DP_PATHOLOGY_RECORD { get; set; }
        public virtual DbSet<DP_TEST_RECORD> DP_TEST_RECORD { get; set; }
        public virtual DbSet<DP_TEST_RESULT> DP_TEST_RESULT { get; set; }
        public virtual DbSet<DP_TEST_RESULT_GERM> DP_TEST_RESULT_GERM { get; set; }
        public virtual DbSet<DP_TRANS_RECORD> DP_TRANS_RECORD { get; set; }
    }
}
