//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.CDR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_ANESTHESIA_RECORD
    {
        public int ANE_REC_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string IN_FLAG { get; set; }
        public string CLINIC_CODE { get; set; }
        public string PATIENT_ID { get; set; }
        public string APPLY_NO { get; set; }
        public string WEIGHT { get; set; }
        public Nullable<int> ABO_BLOOD_CODE { get; set; }
        public Nullable<int> RH_BLOOD_CODE { get; set; }
        public string OPERATION_CODE { get; set; }
        public string OPERATION_NAME { get; set; }
        public string POSITION_CODE { get; set; }
        public string POSITION_NAME { get; set; }
        public string ANESTHESIA_CODE { get; set; }
        public string ANESTHESIA_NAME { get; set; }
        public string TRACHEALTUBE_TYPE { get; set; }
        public string ANESTHESIA_DRUG_NAME { get; set; }
        public string ANESTHESIA_POSITION { get; set; }
        public Nullable<int> BREATH_TYPE_CODE { get; set; }
        public string ANESTHESIA_DESC { get; set; }
        public string ROUTINE_MONITOR_NAME { get; set; }
        public string ROUTINE_MONITOR_RESULT { get; set; }
        public string SPECIAL_MONITOR_NAME { get; set; }
        public string SPECIAL_MONITOR_RESULT { get; set; }
        public Nullable<int> COMPLICATION_FLAG { get; set; }
        public string TREATMENT_COURSE { get; set; }
        public string PUNCTURE_COURSE { get; set; }
        public string ASA_GRADE { get; set; }
        public string ANESTHETIC_EFFECT { get; set; }
        public string ANESTHETIC_BEFORE_DRUG { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> ANESTHESIA_START_DATE { get; set; }
        public Nullable<System.DateTime> IN_DATE { get; set; }
        public Nullable<System.DateTime> OUT_DATE { get; set; }
        public string OPERATION_DOCTOR_CODE { get; set; }
        public string OPERATION_DOCTOR_NAME { get; set; }
        public string DRUG_CODE { get; set; }
        public string DRUG_NAME { get; set; }
        public string FREQ_CODE { get; set; }
        public string FREQ_NAME { get; set; }
        public string DRUG_DOSE_UNIT { get; set; }
        public Nullable<decimal> DRUG_DOSE_ONCE { get; set; }
        public Nullable<decimal> DRUG_DOSE_TOT { get; set; }
        public string GYTJ_CODE { get; set; }
        public string GYTJ_NAME { get; set; }
        public Nullable<decimal> TRANSFUSION_BLOOD { get; set; }
        public string TRANSFUSION_BLOOD_UNIT { get; set; }
        public Nullable<System.DateTime> TRANSFUSION_BLOOD_DATE { get; set; }
        public string TRANSFUSION_BREED_CODE { get; set; }
        public string TRANSFUSION_BREED_NAME { get; set; }
        public Nullable<int> BLOOD_TRANREACT_FLAG { get; set; }
        public string OPERATION_ING_INFUSION { get; set; }
        public Nullable<decimal> SHED_BLOOD { get; set; }
        public string ANESTHESIA_DOCTOR { get; set; }
        public Nullable<System.DateTime> ANESTHESIA_DATE { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
