//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.CDR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_CONSULT_RECORD
    {
        public int CONSULT_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string PATIENT_ID { get; set; }
        public Nullable<System.DateTime> CONSULT_DATE { get; set; }
        public string APPLY_DEPT_CODE { get; set; }
        public string CONSULT_DEPT_CODE { get; set; }
        public string REASON { get; set; }
        public string SUGGESTION { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
