//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.CDR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_DICT_CHECKTEST
    {
        public int DICT_ITEM_ID { get; set; }
        public Nullable<int> CHK_CAT_CODE { get; set; }
        public string ITEM_LIST_CODE { get; set; }
        public string ITEM_LIST_NAME { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_UNIT { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
