//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.CDR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_DICT_DIAG
    {
        public string DIAG_CODE { get; set; }
        public string DIAG_ICD { get; set; }
        public string DIAG_NAME { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
