//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.CDR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_DICT_DRUG
    {
        public string DRUG_CODE { get; set; }
        public string DRUG_NAME { get; set; }
        public string GENERIC_NAME { get; set; }
        public string GOODS_NAME { get; set; }
        public string OTHER_NAME { get; set; }
        public string CATEGORY { get; set; }
        public string QUALITY { get; set; }
        public string DOSAGE { get; set; }
        public string SPECS { get; set; }
        public string MIN_UNIT { get; set; }
        public string PACK_SPECS { get; set; }
        public string PACK_UNIT { get; set; }
        public string USAGE_NAME { get; set; }
        public string FREQ_NAME { get; set; }
        public Nullable<decimal> BASE_DOSE { get; set; }
        public string BASE_DOSE_UNIT { get; set; }
        public Nullable<int> OCT_FLAG { get; set; }
        public string PRODUCING_AREA { get; set; }
        public string PRODUCER_NAME { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
