//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.CDR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_INFECTION_RECORD
    {
        public int INFE_REC_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string IN_FLAG { get; set; }
        public string CLINIC_CODE { get; set; }
        public string PATIENT_ID { get; set; }
        public Nullable<int> INFE_NO { get; set; }
        public Nullable<System.DateTime> IN_DATE { get; set; }
        public string IN_DIAG_CODE { get; set; }
        public string IN_DIAG_NAME { get; set; }
        public string IN_DEPT_CODE { get; set; }
        public string IN_DEPT_NAME { get; set; }
        public Nullable<System.DateTime> OUT_DATE { get; set; }
        public string OUT_DIAG_CODE { get; set; }
        public string OUT_DIAG_NAME { get; set; }
        public string OUT_DEPT_CODE { get; set; }
        public string OUT_DEPT_NAME { get; set; }
        public Nullable<System.DateTime> INFE_DATE { get; set; }
        public string INFE_TYPE_CODE { get; set; }
        public string INFE_TYPE_NAME { get; set; }
        public string INFE_POS_CODE { get; set; }
        public string INFE_POS_NAME { get; set; }
        public string INFE_POS_OTHER { get; set; }
        public Nullable<int> IS_BABY_INFE { get; set; }
        public string INFE_DEPT_CODE { get; set; }
        public string INFE_DEPT_NAME { get; set; }
        public string INFE_PROG_CODE { get; set; }
        public string INFE_PROG_NAME { get; set; }
        public string PRED_FACT_CODE { get; set; }
        public string PRED_FACT_NAME { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
