//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.CDR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_MEDICAL_RECORD
    {
        public string PATIENT_NO { get; set; }
        public string PATIENT_ID { get; set; }
        public string CARD_NO { get; set; }
        public Nullable<int> IN_TIMES { get; set; }
        public string PAY_WAY { get; set; }
        public string CASE_NO { get; set; }
        public string PATIENT_NAME { get; set; }
        public string ID_NO { get; set; }
        public Nullable<int> GENDER_CODE { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string AGE { get; set; }
        public Nullable<int> MARI_STAT_CODE { get; set; }
        public string OCCUPATION { get; set; }
        public string PROVINCE { get; set; }
        public string CITY { get; set; }
        public string COUNTY { get; set; }
        public string NATION_NAME { get; set; }
        public string NATIONALITY { get; set; }
        public System.DateTime IN_DATE { get; set; }
        public string IN_AREA_NAME { get; set; }
        public string IN_DEPT_NAME { get; set; }
        public string TRANSFER_DEPT_NAME { get; set; }
        public System.DateTime OUT_DATE { get; set; }
        public string OUT_AREA_NAME { get; set; }
        public string OUT_DEPT_NAME { get; set; }
        public string ACTUAL_IN_DAYS { get; set; }
        public Nullable<int> IN_SOURCE_CODE { get; set; }
        public string OUTPAT_DIAG_CODE { get; set; }
        public string OUTPAT_DIAG_NAME { get; set; }
        public string IN_DIAG_CODE { get; set; }
        public string IN_DIAG_NAME { get; set; }
        public Nullable<System.DateTime> IN_DIAG_DATE { get; set; }
        public string MAIN_DIAG_CODE { get; set; }
        public string MAIN_DIAG_DESC { get; set; }
        public string MAIN_DIAG_IN_CONDITION { get; set; }
        public string MAIN_DIAG_OUT_CONDITION { get; set; }
        public string OTHER_DIAG_CODE { get; set; }
        public string PATHOLOGY_DIAG_CODE { get; set; }
        public string PATHOLOGY_DIAG_NAME { get; set; }
        public string PATHOLOGY_NO { get; set; }
        public string PATHOLOGY_DIAG_CODE2 { get; set; }
        public string PATHOLOGY_DIAG_NAME2 { get; set; }
        public string PATHOLOGY_NO2 { get; set; }
        public string PATHOLOGY_DIAG_CODE3 { get; set; }
        public string PATHOLOGY_DIAG_NAME3 { get; set; }
        public string PATHOLOGY_NO3 { get; set; }
        public string ALLERGY { get; set; }
        public string ALLERGY_DRUG_NAME { get; set; }
        public string RESCUE_TIMES { get; set; }
        public string RESCUE_SUCCESS_TIMES { get; set; }
        public string DEPT_DIRECTOR_NAME { get; set; }
        public string DIRECTOR_NAME { get; set; }
        public string ATTENDING_DOCTOR_NAME { get; set; }
        public string IN_HOS_DOCTOR_NAME { get; set; }
        public string RESPONSIBLE_NURSE { get; set; }
        public string OPERATION_CODE { get; set; }
        public Nullable<System.DateTime> OPERATION_DATE { get; set; }
        public string OPERATION_NAME { get; set; }
        public string POSITION_NAME { get; set; }
        public string CONTINUED_TIME { get; set; }
        public string OPERATION_DOCTOR { get; set; }
        public string ASSISTANT_I { get; set; }
        public string ASSISTANT_II { get; set; }
        public string ANESTHESIA_NAME { get; set; }
        public string ANESTHESIA_GRADE { get; set; }
        public string WOUND_GRADE { get; set; }
        public string ANESTHESIA_DOCTOR { get; set; }
        public string OPERATION_CODE2 { get; set; }
        public Nullable<System.DateTime> OPERATION_DATE2 { get; set; }
        public string OPERATION_NAME2 { get; set; }
        public string POSITION_NAME2 { get; set; }
        public string CONTINUED_TIME2 { get; set; }
        public string OPERATION_DOCTOR2 { get; set; }
        public string ASSISTANT_I2 { get; set; }
        public string ASSISTANT_II2 { get; set; }
        public string ANESTHESIA_NAME2 { get; set; }
        public string ANESTHESIA_GRADE2 { get; set; }
        public string WOUND_GRADE2 { get; set; }
        public string ANESTHESIA_DOCTOR2 { get; set; }
        public string OPERATION_CODE3 { get; set; }
        public Nullable<System.DateTime> OPERATION_DATE3 { get; set; }
        public string OPERATION_NAME3 { get; set; }
        public string POSITION_NAME3 { get; set; }
        public string CONTINUED_TIME3 { get; set; }
        public string OPERATION_DOCTOR3 { get; set; }
        public string ASSISTANT_I3 { get; set; }
        public string ASSISTANT_II3 { get; set; }
        public string ANESTHESIA_NAME3 { get; set; }
        public string ANESTHESIA_GRADE3 { get; set; }
        public string WOUND_GRADE3 { get; set; }
        public string ANESTHESIA_DOCTOR3 { get; set; }
        public Nullable<int> SPECIAL_NURSING_DAYS { get; set; }
        public Nullable<int> NURSING_DAYS_I { get; set; }
        public Nullable<int> NURSING_DAYS_II { get; set; }
        public Nullable<int> NURSING_DAYS_III { get; set; }
        public string ICU_NAME { get; set; }
        public Nullable<System.DateTime> ICU_IN_DATE { get; set; }
        public Nullable<System.DateTime> ICU_OUT_DATE { get; set; }
        public string ICU_NAME2 { get; set; }
        public Nullable<System.DateTime> ICU_IN_DATE2 { get; set; }
        public Nullable<System.DateTime> ICU_OUT_DATE2 { get; set; }
        public string ICU_NAME3 { get; set; }
        public Nullable<System.DateTime> ICU_IN_DATE3 { get; set; }
        public Nullable<System.DateTime> ICU_OUT_DATE3 { get; set; }
        public Nullable<int> ABO_BLOOD_CODE { get; set; }
        public Nullable<int> RH_BLOOD_CODE { get; set; }
        public string TRANSFUSION_REACTION { get; set; }
        public string RED_BLOOD_DELL { get; set; }
        public string PLATELET { get; set; }
        public string PLASMA { get; set; }
        public string WHOLE_BLOOD { get; set; }
        public string SELF_BLOOD_RETURN { get; set; }
        public string BABY_IN_WEIGHT { get; set; }
        public string BABY_BIRTH_WEIGHT { get; set; }
        public string BABY_BIRTH_WEIGHT2 { get; set; }
        public string BABY_BIRTH_WEIGHT3 { get; set; }
        public Nullable<int> OUT_WAY_CODE { get; set; }
        public Nullable<decimal> TOTAL_FEE { get; set; }
        public Nullable<decimal> OWN_TOTAL_FEE { get; set; }
        public Nullable<decimal> SERVICE_FEE { get; set; }
        public Nullable<decimal> ORDINARY_TREAT_FEE { get; set; }
        public Nullable<decimal> NURSING_FEE { get; set; }
        public Nullable<decimal> ZHYLFWLQT_FEE { get; set; }
        public Nullable<decimal> PATHOLOGY_DIAG_FEE { get; set; }
        public Nullable<decimal> TEST_FEE { get; set; }
        public Nullable<decimal> CHECK_FEE { get; set; }
        public Nullable<decimal> CLINICAL_DIAG_FEE { get; set; }
        public Nullable<decimal> TREAT_WITHOUT_OP_FEE { get; set; }
        public Nullable<decimal> PHYSICS_TREAT_FEE { get; set; }
        public Nullable<decimal> OP_TREAT_FEE { get; set; }
        public Nullable<decimal> ANESTHESIA_FEE { get; set; }
        public Nullable<decimal> OP_FEE { get; set; }
        public Nullable<decimal> RECOVERY_FEE { get; set; }
        public Nullable<decimal> CN_MEDICINE_TREAT_FEE { get; set; }
        public Nullable<decimal> WEST_MEDICINE_FEE { get; set; }
        public Nullable<decimal> ANTIBACTERIALS_FEE { get; set; }
        public Nullable<decimal> CN_PATENT_MEDICINE_FEE { get; set; }
        public Nullable<decimal> CN_HERBAL_MEDICINE_FEE { get; set; }
        public Nullable<decimal> BLOOD_FEE { get; set; }
        public Nullable<decimal> BDBLZP_FEE { get; set; }
        public Nullable<decimal> QDBLZP_FEE { get; set; }
        public Nullable<decimal> NXYZLZP_FEE { get; set; }
        public Nullable<decimal> XBYZLZP_FEE { get; set; }
        public Nullable<decimal> CHECK_MATERIAL_FEE { get; set; }
        public Nullable<decimal> TREAT_MATERIAL_FEE { get; set; }
        public Nullable<decimal> OTHER_FEE { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
