//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.CDR
{
    using System;
    using System.Collections.Generic;
    
    public partial class DP_OPERATION_RECORD
    {
        public int OP_REC_ID { get; set; }
        public string PATIENT_NO { get; set; }
        public string IN_FLAG { get; set; }
        public string CLINIC_CODE { get; set; }
        public string PATIENT_ID { get; set; }
        public string APPLY_NO { get; set; }
        public string PREOPERATIVE_DIAG { get; set; }
        public string POSTOPERATIVE_DIAG { get; set; }
        public Nullable<int> EMERGENCY_INDICATOR { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<System.DateTime> IN_DATE { get; set; }
        public Nullable<System.DateTime> OUT_DATE { get; set; }
        public string OPERATION_TYPE { get; set; }
        public string EQUIPMENT_TYPE { get; set; }
        public Nullable<int> EQUIPMENT_COUNT { get; set; }
        public string OPERATION_CODE { get; set; }
        public string OPERATION_NAME { get; set; }
        public string OPERATION_GRADE { get; set; }
        public string WOUND_GRADE { get; set; }
        public string POSITION_NAME { get; set; }
        public string OPERATION_COURSE { get; set; }
        public Nullable<int> OPERATION_HISTORY_FLAG { get; set; }
        public string SKIN_DISINFECTION { get; set; }
        public Nullable<decimal> SHED_BLOOD { get; set; }
        public Nullable<decimal> TRANSFUSION_BLOOD { get; set; }
        public Nullable<decimal> INFUSION { get; set; }
        public string PREOPERATIVE_DRUG { get; set; }
        public string OPERATION_ING_DRUG { get; set; }
        public string OPERATION_DOCTOR_CODE { get; set; }
        public string OPERATION_DOCTOR_NAME { get; set; }
        public Nullable<System.DateTime> OPERATION_DATE { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
