//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.PDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDP_ERROR_LOG
    {
        public int ERROR_LOG_ID { get; set; }
        public Nullable<int> SD_ID { get; set; }
        public Nullable<int> PROC_TYPE { get; set; }
        public string PROC_URL { get; set; }
        public string DLL_NAME { get; set; }
        public string CLASS_NAME { get; set; }
        public string FUNC_NAME { get; set; }
        public string ERR_CONTENT { get; set; }
        public string UPD_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
