//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.PDP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDPEntities : DbContext
    {
        public PDPEntities()
            : base("name=PDPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PDP_DB_CONF> PDP_DB_CONF { get; set; }
        public virtual DbSet<PDP_ERROR_LOG> PDP_ERROR_LOG { get; set; }
        public virtual DbSet<PDP_PROC_LOG> PDP_PROC_LOG { get; set; }
        public virtual DbSet<PDP_PROC_STAT> PDP_PROC_STAT { get; set; }
        public virtual DbSet<PDP_PROJECT> PDP_PROJECT { get; set; }
        public virtual DbSet<SD_CAT_CONF> SD_CAT_CONF { get; set; }
        public virtual DbSet<SD_CPAT_DETAIL> SD_CPAT_DETAIL { get; set; }
        public virtual DbSet<SD_CPATS> SD_CPATS { get; set; }
        public virtual DbSet<SD_EKPI_FORMULA> SD_EKPI_FORMULA { get; set; }
        public virtual DbSet<SD_EKPI_INFO> SD_EKPI_INFO { get; set; }
        public virtual DbSet<SD_EKPI_PARAM> SD_EKPI_PARAM { get; set; }
        public virtual DbSet<SD_EPKI_VALUE> SD_EPKI_VALUE { get; set; }
        public virtual DbSet<SD_FILTER_INFO> SD_FILTER_INFO { get; set; }
        public virtual DbSet<SD_INFO> SD_INFO { get; set; }
        public virtual DbSet<SD_ITEM_DEP> SD_ITEM_DEP { get; set; }
        public virtual DbSet<SD_ITEM_INFO> SD_ITEM_INFO { get; set; }
        public virtual DbSet<SD_ITEM_OPTION> SD_ITEM_OPTION { get; set; }
        public virtual DbSet<PDP_SD_ITEM_VALUE> SD_ITEM_VALUE { get; set; }
    }
}
