//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.PDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_CAT_CONF
    {
        public int CAT_ID { get; set; }
        public string CAT_CODE { get; set; }
        public string CAT_NAME { get; set; }
        public string CAT_TYPE_CODE { get; set; }
        public string CAT_TYPE_NAME { get; set; }
        public string CAT_PA_CODE { get; set; }
        public string CAT_PA_NAME { get; set; }
        public string CAT_SUB_CODE { get; set; }
        public string CAT_SUB_NAME { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
        public string UPD_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
