//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.PDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_EKPI_INFO
    {
        public int SD_EKPI_ID { get; set; }
        public Nullable<int> SD_ID { get; set; }
        public string SD_CODE { get; set; }
        public string SD_EKPI_CODE { get; set; }
        public string SD_EKPI_NAME { get; set; }
        public string SD_EKPI_ALIAS { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
        public Nullable<int> SD_EKPI_CAT { get; set; }
        public Nullable<int> IS_POSITIVE { get; set; }
        public string SD_EKPI_ALGO { get; set; }
        public Nullable<int> IS_RSN { get; set; }
        public Nullable<int> IS_DISTRIBUTION { get; set; }
        public Nullable<int> IS_TREND { get; set; }
        public int VALID_FLAG { get; set; }
        public string UPD_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string SD_EKPI_DESC { get; set; }
    }
}
