//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.PDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_FILTER_INFO
    {
        public int SD_FILTER_ID { get; set; }
        public int SD_ID { get; set; }
        public string SD_CODE { get; set; }
        public string SD_FILTER_CODE { get; set; }
        public string SD_FILTER_NAME { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
        public string SD_FILTER_ALGO { get; set; }
        public int VALID_FLAG { get; set; }
        public string UPD_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
