//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.PDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_ITEM_INFO
    {
        public int SD_ITEM_ID { get; set; }
        public Nullable<int> SD_ID { get; set; }
        public string SD_CODE { get; set; }
        public string SD_ITEM_CODE { get; set; }
        public string SD_ITEM_NAME { get; set; }
        public string SD_ITEM_ALIAS { get; set; }
        public int SD_ITEM_CAT_ID { get; set; }
        public string SD_ITEM_DATA_TYPE { get; set; }
        public string SD_ITEM_UNIT { get; set; }
        public Nullable<int> NUM_PRECISION { get; set; }
        public int SD_ITEM_SRC { get; set; }
        public Nullable<int> IS_RESULT { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
        public string SD_ITEM_ALGO { get; set; }
        public int VALID_FLAG { get; set; }
        public string UPD_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string SD_EKPI_DESC { get; set; }
        public string COM_SD_ITEM_CODE { get; set; }
        public Nullable<int> COM_SD_ID { get; set; }
    }
}
