//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingCenterSystem.Models.PDP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_ITEM_DEP
    {
        public int SD_ITEM_ID { get; set; }
        public int DEP_SD_ITEM_ID { get; set; }
        public string UPD_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    }
}
